#!/usr/bin/env bash
# Launches vpm-upload-api (builds it first if the binary is missing).
set -euo pipefail

usage() {
  cat <<'HELP'
Launches vpm-upload-api (builds it first if the binary is missing).

Usage:
  ./launch.sh                 # run in foreground (Ctrl-C to stop)
  ./launch.sh --background    # run in background, console logs -> logs/api.log
  ./launch.sh --help

Configuration comes from vpm-shop.conf (copy vpm-shop.conf.example first)
or environment variables (VPM_SHOP, VALIDATOR, MASTER_HOST, BIND,
API_USER, API_PASS, PKG_AUTHOR, RUST_LOG).
HELP
}

cd "$(dirname "$0")"

# --- parse args -----------------------------------------------------------
BACKGROUND=0
NEWTAB=0
case "${1:-}" in
  "" ) ;;
  -b|--background ) BACKGROUND=1 ;;
  -h|--help ) usage; exit 0 ;; 
  -nt|--newtab ) NEWTAB=1 ;;
  * )
    echo "Unknown option: $1" >&2
    usage >&2
    exit 1
    ;;
esac

# --- config ----------------------------------------------------------------
CONF="vpm-shop.conf"

# Generate a default config with credentials if none exists yet.
if [[ ! -f "$CONF" ]]; then
  echo "==> No $CONF found — generating one with default settings ..."
  GEN_USER="${API_USER:-admin}"
  if [[ -n "${API_PASS:-}" ]]; then
    GEN_PASS="$API_PASS"
  elif command -v openssl >/dev/null 2>&1; then
    GEN_PASS="$(openssl rand -hex 12)"
  else
    GEN_PASS="changeme-$(date +%s)"
  fi
  cat > "$CONF" <<EOF
# Generated by launch.sh on first run. Copy to adjust, or edit in place.
# Never commit this file (it holds your credentials/URLs).
VPM_SHOP="${VPM_SHOP:-./mnt/shop}"
VALIDATOR="${VALIDATOR:-./validator/vpmval.dll}"
MASTER_HOST="${MASTER_HOST:-}"
BIND="${BIND:-0.0.0.0:55555}"
PKG_AUTHOR="${PKG_AUTHOR:-VPM Shop}"
API_USER="${GEN_USER}"
API_PASS="${GEN_PASS}"
EOF
  echo "==> Generated $CONF (API_USER=$GEN_USER, API_PASS=$GEN_PASS)"
  echo "    Edit $CONF to set MASTER_HOST (your public repo URL), credentials, then run ./launch.sh again."
fi










if [[ -f "$CONF" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$CONF"
  set +a
fi

BIND="${BIND:-0.0.0.0:55555}"

# Always stop any existing vpm-upload-api bound to our port before launching
# (works for both background and foreground runs, no pid file needed).
PORT="${BIND##*:}"
echo "==> Stopping any process on port $PORT ..."
if command -v fuser >/dev/null 2>&1; then
  fuser -k "${PORT}/tcp" >/dev/null 2>&1 || true
else
  # no fuser — fall back to ss to find and kill listeners on the port
  for pid in $(ss -ltnp 2>/dev/null | grep ":$PORT " | grep -oP 'pid=\K[0-9]+' | sort -u); do
    kill "$pid" 2>/dev/null || true
  done
fi
# give the port time to free up
sleep 1

# Create the default shop directory if it doesn't exist yet.
mkdir -p "${VPM_SHOP:-./mnt/shop}"

BIN="target/release/vpm-upload-api"

#if [[ ! -x "$BIN" ]]; then
#  echo "==> Binary not found, running ./build.sh first ..."
echo "==> Building vpm-upload-api ..." 
  ./build.sh
#fi

echo "==> Launching vpm-upload-api (listening on $BIND)"
mkdir -p logs

URL="http://localhost:${BIND##*:}/"

# launch browser tab flag — open after server is up
if [[ "$NEWTAB" == "1" ]]; then
  open_browser() {
    if command -v xdg-open >/dev/null 2>&1; then
      xdg-open "$URL"
    elif command -v open >/dev/null 2>&1; then
      open "$URL"
    else
      echo "==> Could not open browser tab (no xdg-open/open found)"
    fi
  }
else
  open_browser() { :; }
fi

if [[ "$BACKGROUND" == "1" ]]; then
  LOG="logs/api.log"
  nohup "$BIN" >>"$LOG" 2>&1 &
  PID=$!
  echo "==> Started in background (pid $PID) — console logs: $LOG"
  # brief wait so server can bind before opening tab
  sleep 1
  open_browser
else
  "$BIN" &
  PID=$!
  # allow server to bind, then open tab
  sleep 1
  open_browser
  wait "$PID"
fi